name: "Publish"

on:
  push:
    branches: [ beta ]

jobs:
  # quality:
  #   name: Test Library
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         cache: npm
  #     - run: npm ci
  #     - run: npx jest --coverage

  publish:
    name: Publish Beta
    runs-on: ubuntu-latest
    # needs: [quality]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release --dry-run --branches beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}